<?php
$translate = $this->plugin('translate');
// Prepare the property queries.
$properties = isset($query['property']) ? $query['property'] : [];
$properties = array_filter($properties, function ($value) {
    return isset($value['text']) ? '' !== trim($value['text']) : true;
});
if (!$properties) {
    $properties[] = [];
}

if (isset($query['search'])) {
    unset($properties[0]['joiner']);
    array_unshift($properties, [
        'property' => '',
        'type' => 'in',
        'text' => $query['search']
    ]);
}

$queryOption = function ($value, array $search, $key, $text) {
    $selected = null;
    if (isset($search[$key]) && $value === $search[$key]) {
        $selected = ' selected';
    }
    return sprintf('<option value="%s"%s>%s</option>', $value, $selected, $text);
};
$queryText = function (array $search, $index) {
    $text = isset($search['text']) ? $search['text'] : null;
    return sprintf(
        '<input type="text" class="query-text form-control" name="%s" value="%s" aria-label="%s">',
        $this->escapeHtml("property[$index][text]"),
        $this->escapeHtml($text),
        $this->escapeHtml($this->translate('Query text'))
    );
};

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');
$siteSetting = $plugins->get('siteSetting');
$isSiteRequest = $this->status()->isSiteRequest();
$usedTerms = $isSiteRequest ? $siteSetting('advancedsearchplus_restrict_used_terms', true) : $setting('advancedsearchplus_restrict_used_terms', true);
?>

<div id="property-queries" class="field removable multi-value mt-4" role="group" aria-labelledby="by-value-label">
    <div class="field-meta my-2">
        <div>
            <button style="border-radius: 40px;" type="button" class="add-value o-icon-add btn btn-secondary btn-sm"
                aria-label="<?php echo $translate('Add new value'); ?>"
                title="<?php echo $translate('Add new value'); ?>"><i
                    class="fa-solid fa-circle-plus"></i>&nbsp;&nbsp;<?php echo $translate('Add new value'); ?></button>
        </div>
    </div>
    <div class="inputs">
        <?php
        $index = 0;
        foreach ($properties as $property):
        $stem = "property[$index]";
        ?>
        <div class="mb-2 value row row-auto">
            <!-- align-items-center -->
            <div class="mb-1 col-auto">

                <select style="border-radius: 40px;" class="joiner form-select"
                    name="<?php echo $this->escapeHtml($stem . '[joiner]'); ?>">
                    <?php echo $queryOption('and', $property, 'joiner', $translate('AND')); ?>
                    <?php echo $queryOption('or', $property, 'joiner', $translate('OR')); ?>
                </select>
            </div>
            <div class="mb-1 col-auto">
                <?php echo $this->propertySelect([
                    'name' => $stem . '[property]',
                    'attributes' => [
                        'class' => 'query-property form-select',
                        'value' => isset($property['property']) ? $property['property'] : null,
                        'aria-label' => $translate('Property'),
                        "style" => "border-radius: 40px;"
                    ],
                    'options' => [
                        'empty_option' => '[Any Property]', // @translate
                        'apply_templates' => $this->status()->isSiteRequest() ? $this->siteSetting('search_apply_templates') : false,
                        'used_terms' => $usedTerms,
                    ]
                ]); ?>
            </div>
            <div class="mb-1 col-auto">
                <select style="border-radius: 40px;" class="query-type form-select"
                    name="<?php echo $this->escapeHtml($stem . '[type]'); ?>"
                    aria-label="<?php echo $translate('Query type'); ?>">
                    <?php echo $queryOption('in', $property, 'type', $translate('contains')); ?>
                    <?php echo $queryOption('nin', $property, 'type', $translate('does not contain')); ?>
                    <?php echo $queryOption('eq', $property, 'type', $translate('is exactly')); ?>
                    <?php echo $queryOption('neq', $property, 'type', $translate('is not exactly')); ?>

                    <?php echo $queryOption('res', $property, 'type', $translate('is resource with ID')); ?>
                    <?php echo $queryOption('nres', $property, 'type', $translate('is not resource with ID')); ?>
                    <?php echo $queryOption('ex', $property, 'type', $translate('has any value')); ?>
                    <?php echo $queryOption('nex', $property, 'type', $translate('has no values')); ?>
                </select>
            </div>
            <div class="mb-1 col-auto">
                <div class="input-group" style="border-radius: 40px;">
                    <?php echo $queryText($property, $index); ?>
                    <button type="button" class="o-icon-delete remove-value btn btn-outline-danger"
                        aria-label="<?php echo $translate('Remove value'); ?>"
                        title="<?php echo $translate('Remove value'); ?>"><i
                            class="fa-solid fa-circle-xmark"></i></button>
                </div>
            </div>
        </div>
        <?php
        $index++;
        endforeach;
        ?>
    </div>
</div>