<?php
$color = $this->themeSetting('stylesheet');
(!$color) ? $color = "light" : '';
?>
<!--Navbar-->
<nav class="navbar navbar-<?php echo $color; ?> bg-<?php echo $color; ?> navbar-expand-lg">
  <div class="container-fluid"> <a href="<?php echo $site->url(); ?>" class="navbar-brand"><?php echo $site->title(); ?></a> <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basicExampleNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
      <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'dropdown']); ?>
      <div class="d-flex">
        <?php echo $this->partial('common/search-form'); ?> </div>
    </div>
    <!-- Collapsible content -->
  </div>
</nav>
<!--/.Navbar-->