<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);
?>
<div id="linked-resources">
<div class="linked-header">
    <div id="linked-filter">
        <div class="form-group row">
            <label for="staticEmail" class="col-sm-4 col-form-label"><?php echo $translate('Filter by property'); ?></label>
            <div class="col-sm-8">
                <select id="filter-property" class="form-control" name="property" data-url="<?php echo $escape($this->url(null, [], true)); ?>" data-fragment="<?php echo $escape($fragment); ?>">
                    <option value=""><?php echo $translate('All'); ?></option>
                    <?php foreach ($properties as $prop): ?>
                    <option value="<?php echo $escape($prop->id()); ?>"<?php echo $prop->id() == $property ? ' selected="selected"' : ''; ?>><?php echo $escape(sprintf('%s (%s)', $prop->label(), $prop->term())); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
    <?php echo ($totalCount > $perPage) ? $pagination : ''; ?>
</div>

<?php foreach ($subjectValues as $term => $values): ?>
    <div class="card my-4">
        <div class="card-header">
            <?php echo $escape($this->translate($values[0]->property()->label())); ?>
        </div>
        <div class="card-body">
<table class="table">
<thead>
    <tr>
    <th><?php echo $translate('Title'); ?></th>
    <th><?php echo $translate('Alternate label'); ?></th>
    <th><?php echo $translate('Class'); ?></th>
    </tr>
</thead>
<tbody>
    <?php foreach ($values as $value): ?>
    <?php
    $template = $value->resource()->resourceTemplate();
    $templateProperty = $template ? $template->resourceTemplateProperty($value->property()->id()) : null;
    $altLabel = $templateProperty ? $templateProperty->alternateLabel() : null;
    ?>
    <tr class="linked-resource">
        <td><?php echo $value->resource()->linkPretty(); ?></td>
        <td>
        <?php if ($altLabel): ?>
        <span class="alternate-label"><?php echo $this->escapeHtml($altLabel); ?></span>
        <?php endif; ?>
        </td>
        <td>
        <?php if ($value->resource()->resourceClass()): ?>
        <span class="resource-class"><?php echo $this->escapeHtml($value->resource()->resourceClass()->label()); ?></span>
        <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>
</div>
</div>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
