<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<style>
    .resource-link img {
        width: 90px;
        margin-bottom: 10px;
        margin-right: 10px;
    }
</style>

<div class="table-responsive">
    <table class="table table-striped">
        <tbody>
            <?php foreach ($values as $term => $propertyData): ?>
            <tr>
                <td width="15%"><?php if ($propertyData['alternate_label']): ?>
                    <?php echo $escape($propertyData['alternate_label']); ?>
                    <?php else: ?>
                    <?php echo $escape($translate($propertyData['property']->label())); ?>
                    <?php endif; ?>
                    <?php if ('term' === $labelInfo): ?>
                    <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
                    <?php elseif ('vocab' === $labelInfo): ?>
                    <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
                    <?php endif; ?>
                </td>
                <td><?php foreach ($propertyData['values'] as $value): ?>
                    <?php
                        $valueType = $value->type();
                        $class = ['value'];
                        if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                            $class[] = 'resource';
                            $class[] = $escape($value->valueResource()->resourceName());
                        } elseif ('uri' == $valueType) {
                            $class[] = 'uri';
                        }
                        if (!$value->isPublic()) {
                            $class[] = 'private';
                        }
                        ?>
                    <div class="<?php echo implode(' ', $class); ?>"
                        lang="<?php echo $escape($value->lang()); ?>">
                        <?php if ($language = $value->lang()): ?>
                        <span class="badge badge-pill px-3" style="background-color : #78909c;"><?php echo $language; ?></span>
                        <?php endif; ?>
                        <?php echo $value->asHtml(); ?>
                    </div>
                    <?php endforeach; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>