<?php $escape = $this->plugin('escapeHtml'); $translate = $this->plugin('translate'); ?>
<?php if (count($filters) > 0): ?>
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
        <span class="badge rounded-pill bg-secondary p-2 px-3 m-1">
            <span class="filter-label">
                <?php echo $escape($filterLabel); ?>
            </span>

            <?php foreach ($filterValues as $filterValue): ?>
                <span class="filter-value"><?php echo $escape($filterValue); ?></span>
            <?php endforeach; ?>
        </span>
        <?php if ($filterLabel != "テンプレート"): ?> <!-- 要改善 -->
        <?php endif; ?>
    <?php endforeach; ?>
            
<?php endif; ?>
