<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'item-sets search');
?>

<div class="container mt-4 mb-5">
    <h3><?php echo $translate('Collection'); ?>
        <?php echo $translate('Search'); ?>
    </h3>
    <form id="advanced-search" method="get"
        action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
        <?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'itemSet']
); ?>
        <div id="page-actions mt-4">
            <input style="border-radius: 40px;" class="px-3 btn btn-primary" type="submit" name="submit"
                value="<?php echo $this->escapeHtml($translate('Search')); ?>">
        </div>
    </form>
</div>