<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php $this->trigger('view.show.before'); ?>

<div class="container mt-4 mb-5" style="word-wrap : break-word;">
<div class="my-5">
<?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
</div>

<!-- <h3><?php echo $translate('Item'); ?></h3> -->


<div class="my-5">
<?php echo $this->resourcePageBlocks($item)->getBlocks(); ?>
</div>

<div class="my-5 pb-5 text-center">
            <div>
                <b><?php echo $translate('Date Created'); ?>
                </b>
                <div>
                    <?php echo $escape($this->i18n()->dateFormat($item->created())); ?>
                </div>
            </div>
            
            <div class="mt-4">
                <b><?php echo $translate('Date Modified'); ?>
                </b>
                <div>
                    <?php echo $escape($this->i18n()->dateFormat($item->modified())); ?>
                </div>
            </div>
        </div>

<?php $this->trigger('view.show.after'); ?>
</div>
