<?php
$translate = $this->plugin('translate');
$item = $media->item();

$this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<div class="container mt-4 mb-5" style="word-wrap : break-word;">

<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<!-- <h3><?php echo $translate('Media'); ?></h3> -->
<?php $this->trigger('view.show.before'); ?>
<p class="media-parent-item mt-5">
    <?php echo sprintf($translate('Part of %s'), $item->link($item->displayTitle())); ?>
</p>

<div class="mt-5">

<?php echo $media->render(); ?>

</div>

<div class="mt-5 mb-4">

        <div class="card-body pt-4">

<?php echo $media->displayValues(); ?>

</div>

</div>

<?php $this->trigger('view.show.after'); ?>

</div>
