<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchPage->subSetting('facet', 'facets'))) {
    return;
}

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>


<?php if ($displayActive && count($activeFacets)): ?>

<div class="mb-3">

    <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetValue): ?>

    <span class="badge rounded-pill bg-secondary m-1 py-2 px-3">
        <?= $facetActive($name, ['value' => $facetValue, 'count' => null], $options) ?>
    </span>
    <?php endforeach; ?>

</div>

<?php endif; ?>

<form id="form-facets">

    <?php if ($displayFacetButton): ?>
    <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
    <?php endif; ?>

    <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>

    <div class="">
        <button style="border-radius: 40px;" type="submit" class="btn btn-dark">
            <?= $translate('Apply facets') ?>
        </button>
    </div>
    <?php endif; ?>

    <?php if (empty($facets) && empty($activeFacets)): ?>
    <p><?= $translate('No facets.') ?>
    </p>
    <?php else: ?>

    <?php foreach ($facets as $name => $facetValues): ?>

    <div class="card mt-4" style="">
        <div class="card-header">
            <!-- card-header p2 -->
            <?= $translate($facetLabel($name)) ?>
        </div>
        <div class="card-body">
            <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
            <?= $facetSelect($name, $facetValues, $options) ?>
            <?php else: ?>
            <?= $facetElements($name, $facetValues, $options) ?>
            <?php endif; ?>
        </div>
    </div>
    <!--
                <h4></h4>
                <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
    <?= $facetSelect($name, $facetValues, $options) ?>
    <?php else: ?>
    <?= $facetElements($name, $facetValues, $options) ?>
    <?php endif; ?>
    -->
    <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>

    <div class="mt-4">
        <button style="border-radius: 40px;" type="submit" class="btn btn-dark">
            <?= $translate('Apply facets') ?>
        </button>
    </div>

    <?php endif; ?>

</form>