<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.min.css'));
//$this->headLink()->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css');
$this->headLink()->prependStylesheet($this->assetUrl('fontawesome/css/all.min.css'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile("https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js");
$this->headScript()->prependFile("https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js");
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_', '-', $this->themeSetting('banner_position')) : 'center';
$this->trigger('view.layout');
$userBar = $this->userBar();
$color = $this->themeSetting('stylesheet');
(!$color) ? $color = "light" : '';

$isHomePage = 0;
$top_image = $this->themeSettingAssetUrl('top_image');
try {
    //Nextモジュールが有効でない場合
    $isHomePage = $this->isHomePage();
} catch (Exception $e) {
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>

  <style>
    a {
      text-decoration: none;
    }

    #btn-back-to-top {
      position: fixed;
      bottom: 20px;
      right: 20px;
      display: none;
    }
  </style>
</head>

<?php echo $this->htmlElement('body'); ?>
<!-- <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
-->
<?php echo $userBar; ?>
<?php echo $this->partial('common/header-vertical'); ?>

<?php if ($isHomePage && $top_image): ?>
<style>
  .boxbackground {
    position: relative;
    width: 100%;
    background: url("<?php echo $top_image; ?>") no-repeat center center;
    background-size: cover;
  }
</style>

<div class="boxbackground">
  <div style="background: rgba(0, 0, 0, 0.5);">
    <div class="container">

      <div class="row py-5 text-white text-center">
        <div class="col-xl-9 mx-auto my-5">

          <?php if ($site_sub_title = $this->themeSetting('site_sub_title')): ?>
          <h4 class="mb-3">
            <?php echo $site_sub_title; ?>
          </h4>
          <?php endif; ?>

          <h1>
            <?php echo $siteTitle; ?>
          </h1>
          <?php if ($site_summary = $site->summary()): ?>
          <p class="mt-3">
            <?php echo $site_summary; ?>
          </p>
          <?php endif; ?>

          <?php if ($top_url = $this->themeSetting('top_url')): ?>
          <a href="<?php echo $top_url; ?>"
            class="mt-3 btn btn-danger px-3" style="border-radius: 40px;">
            <i class="fa-solid fa-magnifying-glass"></i> <?php echo $this->translate('Browse'); ?>
          </a>
          <?php endif; ?>
        </div>
      </div>

    </div>
  </div>
</div>
<?php endif; ?>


<div id="content" role="main">
  <?php echo $this->content; ?>
</div>


<!-- Footer -->
<footer class="py-5 navbar-dark bg-dark text-center">
  <div class="container-fluid">
    <p class="my-0 text-white">
      <!-- text-muted -->
      <small>
        <?php if ($footerContent = $this->themeSetting('footer')): ?>
        <?php echo $footerContent; ?>
        <?php else: ?>
        <?php echo $this->translate('Powered by Omeka S'); ?>
        <?php endif; ?>
      </small>
    </p>
  </div>
</footer>

<button type="button" class="btn btn-danger btn-lg" style="border-radius: 10px;" id="btn-back-to-top">
  <i class="fa-solid fa-arrow-up"></i>
</button>



<script>
  //Get the button
  let mybutton = document.getElementById("btn-back-to-top");

  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function() {
    scrollFunction();
  };

  function scrollFunction() {
    if (
      document.body.scrollTop > 20 ||
      document.documentElement.scrollTop > 20
    ) {
      mybutton.style.display = "block";
    } else {
      mybutton.style.display = "none";
    }
  }
  // When the user clicks on the button, scroll to the top of the document
  mybutton.addEventListener("click", backToTop);

  function backToTop() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>
<style>
  #btn-back-to-top {
    position: fixed;
    bottom: 20px;
    right: 20px;
    display: none;
  }
</style>
</body>

</html>