name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Read version and name from config
        id: read-config
        run: |
          version=$(grep 'version' ./config/module.ini | cut -d '=' -f2 | tr -d ' "' | tr -d "\r")
          echo "::set-output name=version::$version"
          echo "::set-output name=name::IiifViewers"

      - name: Prepare release
        run: |
          version=${{ steps.read-config.outputs.version }}
          name=${{ steps.read-config.outputs.name }}
          echo "Preparing release for $name version $version"
          rsync -ahv . "./$name" --exclude '.*' --exclude '*.sh'
          zip -r "./$name-$version.zip" "./$name"
          rm -rf "./$name"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.read-config.outputs.name }}-${{ steps.read-config.outputs.version }}.zip
          asset_name: ${{ steps.read-config.outputs.name }}-${{ steps.read-config.outputs.version }}.zip
          asset_content_type: application/zip
